services:
  postgres:
    image: postgres:16
    container_name: traderefer-postgres
    environment:
      POSTGRES_USER: traderefer
      POSTGRES_PASSWORD: traderefer
      POSTGRES_DB: traderefer
    ports:
      - "5432:5432"
    volumes:
      - traderefer-pg-data:/var/lib/postgresql/data

volumes:
  traderefer-pg-data:
